version: 2
updates:
- package-ecosystem: docker
  directory: "./ansible/roles"
  schedule:
    interval: "daily"
    time: "05:31"
  target-branch: main
  labels:
  - dependency_updates
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "05:31"
  target-branch: main
  labels:
    - dependency_updates
- package-ecosystem: "gitsubmodule"
  directory: "./src"
  schedule:
    interval: "daily"
    time: "05:31"
  target-branch: main
  labels:
    - dependency_updates
