---
- name: Create and maintain a datalab
  hosts: all
  vars:
    # root behaves differently than other users; set home dir accordingly
    ansible_user_home_dir: "{{ '/' + ansible_ssh_user if ansible_ssh_user == 'root' else '/home/' + ansible_ssh_user }}"
  roles:
    - role: preflight
      name: Check if the system is ready for the playbook
      tags: [setup]
    - role: setup
      name: Run OS and disk set up tasks
      tags: [setup]
    - role: docker
      name: Install and configure Docker
      tags: [setup]
    - role: fail2ban
      name: Install and configure fail2ban
      tags: [setup]
    - role: ssl_first_run
      name: Run stripped down nginx and SSL for the first time
      tags: [setup, ssl]
    - role: datalab
      name: Build and launch datalab services
      tags: [setup, deploy]
    - role: nginx
      name: Launch nginx container with autorenewing certbot
      tags: [setup, maintenance, ssl]
    - role: borg
      name: Configure borg(matic) and remote backups
      tags: [borg]

  tasks:
    - name: Keep all packages up-to-date
      ansible.builtin.include_role:
        name: apt_upgrade
        apply:
          tags: [maintenance]
      tags: [maintenance]
