---
collections:
  - name: community.docker
    version: 3.10.2
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.2.0
  - name: community.crypto
    version: 2.21.1
roles:
  - name: borgbase.ansible_role_borgbackup
    version: v1.0.1
