---
- name: Upgrade packages (Debian)
  become: true
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400

- name: Upgrade packages (RedHat)
  become: true
  when: ansible_os_family == 'RedHat'
  ansible.builtin.dnf:
    name: '*'
    state: latest  # noqa: package-latest
